spring:
  application:
    name: auth-service

server:
  port: ${SERVER_PORT:8084}

app:
  api-key: ${API_KEY:auth-service-key}
  api-key-header: X-API-KEY

management:
  endpoints:
    web:
      exposure:
        include: health,info
